import { StyleSheet } from 'react-native';
import type { getTheme } from './theme';

export function formatSavedAt(value: string): string {
  try {
    return new Intl.DateTimeFormat(undefined, {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    }).format(new Date(value));
  } catch {
    return value;
  }
}

export function createMobileStyles(theme: ReturnType<typeof getTheme>) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.colors.bg,
    },
    scroll: {
      paddingHorizontal: theme.spacing.pageX,
      paddingTop: theme.spacing.pageTop,
      paddingBottom: 40,
      backgroundColor: theme.colors.bg,
      flexGrow: 1,
    },
    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.colors.bg,
    },
    topbar: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    wordmark: {
      fontSize: theme.type.small,
      textTransform: 'uppercase',
      letterSpacing: 1.4,
      color: theme.colors.textSecondary,
      fontFamily: theme.fonts.mono,
    },
    topbarMeta: {
      fontSize: theme.type.micro,
      textTransform: 'uppercase',
      letterSpacing: 1.1,
      color: theme.colors.textTertiary,
      fontFamily: theme.fonts.mono,
    },
    title: {
      fontSize: theme.type.hero,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      marginBottom: 10,
    },
    subtitle: {
      fontSize: theme.type.body,
      color: theme.colors.textSecondary,
      marginBottom: 24,
      lineHeight: 22,
    },
    card: {
      backgroundColor: theme.colors.surfaceSolid,
      borderRadius: theme.radii.card,
      padding: theme.spacing.cardPad,
      marginBottom: theme.spacing.sectionGap,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    sectionLabel: {
      fontSize: theme.type.micro,
      textTransform: 'uppercase',
      letterSpacing: 1.1,
      color: theme.colors.textSecondary,
      fontFamily: theme.fonts.mono,
      opacity: 0.72,
      marginBottom: 10,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      marginBottom: 8,
    },
    muted: {
      fontSize: theme.type.body,
      color: theme.colors.textSecondary,
      marginBottom: 16,
      lineHeight: 22,
    },
    inlineStrong: {
      fontWeight: '600',
      color: theme.colors.textPrimary,
    },
    button: {
      backgroundColor: theme.colors.accent,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 10,
      alignItems: 'center',
    },
    secondary: {
      backgroundColor: 'transparent',
      borderWidth: 1,
      borderColor: theme.colors.border,
      marginTop: 10,
    },
    buttonText: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.bg,
    },
    buttonTextSecondary: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textPrimary,
    },
    error: {
      color: theme.colors.accentDestructive,
      marginTop: 8,
      fontFamily: theme.fonts.mono,
      fontSize: theme.type.small,
    },
    status: {
      color: theme.colors.success,
      marginTop: 12,
      fontSize: theme.type.small,
      fontFamily: theme.fonts.mono,
      backgroundColor: theme.colors.successBg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      alignSelf: 'flex-start',
    },
    input: {
      backgroundColor: theme.colors.inputBg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 8,
      paddingHorizontal: 14,
      paddingVertical: 12,
      color: theme.colors.textPrimary,
      fontSize: theme.type.body,
      marginBottom: 12,
    },
    settingsScroll: {
      paddingHorizontal: 20,
      paddingTop: 152,
      paddingBottom: 48,
      backgroundColor: theme.colors.bg,
      flexGrow: 1,
    },
    settingsTitle: {
      color: theme.colors.textPrimary,
      fontFamily: theme.fonts.mono,
      fontSize: 24,
      lineHeight: 32,
      textAlign: 'center',
      marginBottom: 38,
    },
    settingsCard: {
      backgroundColor: theme.name === 'dark' ? 'rgba(30,30,30,0.82)' : 'rgba(255,255,255,0.8)',
      borderRadius: 6,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.06)',
      shadowColor: '#000',
      shadowOpacity: theme.name === 'dark' ? 0.18 : 0.04,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    settingsSection: {
      padding: 12,
      gap: 8,
    },
    settingsSectionTitle: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '400',
    },
    settingsSectionValue: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    settingsDivider: {
      height: 1,
      backgroundColor: theme.colors.border,
    },
    settingsDescription: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 22,
    },
    settingsDescriptionStrong: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 22,
      marginTop: 2,
    },
    settingsInput: {
      backgroundColor: theme.colors.inputBg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 4,
      paddingHorizontal: 8,
      paddingVertical: 8,
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 24,
      marginTop: 4,
    },
    vaultModalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.24)',
      justifyContent: 'center',
      paddingHorizontal: 20,
    },
    vaultModalCard: {
      backgroundColor: theme.name === 'dark' ? '#171717' : '#ffffff',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 18,
    },
    vaultModalTitle: {
      color: theme.colors.textPrimary,
      fontFamily: theme.fonts.mono,
      fontSize: 20,
      lineHeight: 28,
      marginBottom: 8,
    },
    vaultModalCopy: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 22,
      marginBottom: 16,
    },
    vaultModalSection: {
      backgroundColor: theme.colors.overlay,
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
      gap: 4,
    },
    vaultModalLabel: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      lineHeight: 18,
      textTransform: 'uppercase',
      fontFamily: theme.fonts.mono,
    },
    vaultModalValue: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      lineHeight: 22,
    },
    vaultModalStatus: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 22,
      marginBottom: 12,
    },
    vaultModalClose: {
      marginTop: 12,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
    },
    vaultModalCloseText: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      fontWeight: '600',
    },
    debugBox: {
      marginTop: 14,
      backgroundColor: theme.colors.overlay,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: 10,
      padding: 12,
    },
    debugTitle: {
      color: theme.colors.textPrimary,
      fontSize: 14,
      fontWeight: '600',
      marginBottom: 8,
      fontFamily: theme.fonts.mono,
      textTransform: 'uppercase',
    },
    debugLine: {
      color: theme.colors.textPrimary,
      fontSize: 13,
      marginBottom: 4,
      fontFamily: theme.fonts.mono,
    },
    debugReason: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
      marginTop: 4,
    },
    logList: {
      marginTop: 4,
    },
    logRow: {
      paddingVertical: 12,
    },
    logRowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    logText: {
      gap: 4,
    },
    logTitle: {
      color: theme.colors.textPrimary,
      fontSize: theme.type.body,
      lineHeight: 21,
      fontWeight: '500',
    },
    logMeta: {
      color: theme.colors.textSecondary,
      fontFamily: theme.fonts.mono,
      fontSize: theme.type.small,
    },
    logsScroll: {
      paddingHorizontal: 16,
      paddingTop: 62,
      paddingBottom: 48,
      backgroundColor: theme.colors.bg,
      flexGrow: 1,
    },
    logsGroups: {
      gap: 32,
    },
    logsGroup: {
      gap: 12,
    },
    logsGroupTitle: {
      color: theme.colors.textPrimary,
      fontFamily: theme.fonts.mono,
      fontSize: 20,
      paddingHorizontal: 16,
    },
    logsGroupCard: {
      backgroundColor: theme.colors.surfaceSolid,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.06)',
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: theme.name === 'dark' ? 0.18 : 0.04,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    logsEntry: {
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 8,
    },
    logsEntryBorder: {
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
    },
    logsEntryMetaRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: 12,
    },
    logsEntrySource: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      flex: 1,
    },
    logsEntryDate: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      textAlign: 'right',
    },
    logsEntryTitle: {
      color: theme.colors.textPrimary,
      fontSize: 17,
      lineHeight: 27,
      fontWeight: '400',
    },
    logsEmptyScroll: {
      paddingHorizontal: 16,
      paddingTop: 62,
      paddingBottom: 48,
      backgroundColor: theme.colors.bg,
      flexGrow: 1,
      justifyContent: 'center',
    },
    logsEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
      paddingHorizontal: 28,
      paddingBottom: 72,
    },
    logsEmptyTitle: {
      color: theme.colors.textPrimary,
      fontFamily: theme.fonts.mono,
      fontSize: 24,
      lineHeight: 40,
      textAlign: 'center',
    },
    logsEmptyCopy: {
      color: theme.colors.textSecondary,
      fontSize: 14,
      lineHeight: 22,
      textAlign: 'center',
      maxWidth: 284,
    },
    logsEmptyAsset: {
      width: 240,
      height: 200,
      marginBottom: 8,
    },
  });
}
